name: Deploy Laravel to FTP

on:
  push:
    branches:
      - servidor

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7  # Puedes usar otra versión si lo necesitas
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: izacvard_g04
          MYSQL_USER: izacvard_g04
          MYSQL_PASSWORD: prY*0iRtU{&X
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Paso 1: Clonar el repositorio
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      # Paso 2: Subir archivos por FTP
      - name: Subir archivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"
          server-dir: "/"

      # Paso 3: Instalar Composer (si es necesario)
      - name: Instalar Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer install --no-interaction --prefer-dist

      # Paso 4: Verificar si las dependencias están instaladas correctamente
      - name: Verificar si composer y dependencias están instaladas
        run: |
          composer install --no-interaction --prefer-dist
          ls -l vendor/

      # Paso 5: Configurar las variables de entorno para la base de datos
      - name: Configurar variables de entorno para la base de datos
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=izacvard_g04" >> .env
          echo "DB_USERNAME=izacvard_g04" >> .env
          echo "DB_PASSWORD=prY*0iRtU{&X" >> .env

      # Paso 6: Ejecutar migraciones
      - name: Ejecutar migraciones
        run: |
          php artisan migrate:fresh --seed --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: izacvard_g04
          DB_USERNAME: izacvard_g04
          DB_PASSWORD: prY*0iRtU{&X
